# Generated by Django 6.0 on 2026-01-18 19:52

import django.contrib.postgres.indexes
import django.db.models.deletion
import main.apps.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=main.apps.core.models.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                        output_field=models.DateTimeField(),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "provider_id",
                    models.CharField(
                        help_text="Should match Allauth SocialApp provider", max_length=255, verbose_name="Provider ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                ("website_url", models.URLField(verbose_name="Website URL")),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProviderUserProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=main.apps.core.models.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                        output_field=models.DateTimeField(),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("config_data", models.JSONField(default=dict, verbose_name="Config data")),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_user_projects",
                        to="providers.provider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_user_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider User Project",
                "verbose_name_plural": "Provider User Projects",
                "ordering": ("-created_at",),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["config_data"], name="providers_p_config__47621d_gin"
                    )
                ],
            },
        ),
    ]
