# Generated by Django 6.0 on 2026-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provideruserproject",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="provideruserproject",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="provideruserproject",
            name="project_id",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Project ID"),
        ),
    ]
