# Generated by Django 6.0 on 2026-01-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0002_provideruserproject_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provideruserproject",
            name="configuration_attempts",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Configuration attempts"),
        ),
        migrations.AddField(
            model_name="provideruserproject",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("configured", "Configured"), ("failed", "Failed")],
                default="pending",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
