# Generated by Django 6.0 on 2026-01-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0003_provideruserproject_configuration_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="setup_instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Instructions on how to setup the Provider Project manually (e.g. through Console)",
                verbose_name="Setup instructions",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="setup_script",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Script that utilizes the provider CLI to setup the Provider Project",
                verbose_name="Setup script",
            ),
        ),
    ]
