# Generated by Django 6.0 on 2026-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0004_provider_setup_instructions_provider_setup_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="setup_script_instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Instructions on how to setup the Provider Project using the setup script",
                verbose_name="Setup script instructions",
            ),
        ),
    ]
