# Generated by Django 6.0 on 2026-01-21 13:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0005_provider_setup_script_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="setup_checklist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512),
                default=list,
                help_text="Checklist of steps to setup the Provider Project",
            ),
        ),
    ]
