# Generated by Django 6.0 on 2026-01-22 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0006_provider_setup_checklist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="provideruserproject",
            constraint=models.UniqueConstraint(
                fields=("provider_id", "user_id", "project_id"), name="unique_provider_user_project_project_id"
            ),
        ),
    ]
