# Generated by Django 6.0 on 2026-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0007_provideruserproject_unique_provider_user_project_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="short_name",
            field=models.CharField(blank=True, default="", max_length=16, verbose_name="Short Name"),
        ),
    ]
