# Generated by Django 6.0 on 2026-01-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0008_provider_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="provideruserproject",
            name="configuration_error",
            field=models.TextField(blank=True, default="", verbose_name="Configuration error"),
        ),
    ]
