# Generated by Django 6.0 on 2026-01-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0009_provideruserproject_configuration_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="validation_script_instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Instructions on how to validate the resources managed by the terraform in provider project",
                verbose_name="Validation script instructions",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="validation_script_template",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Template for the validation script",
                verbose_name="Validation script template",
            ),
        ),
    ]
