# Generated by Django 6.0 on 2026-01-18 19:51

import django.contrib.postgres.indexes
import django.db.models.deletion
import main.apps.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=main.apps.core.models.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                        output_field=models.DateTimeField(),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Tutorial Tag",
                "verbose_name_plural": "Tutorial Tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=main.apps.core.models.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                        output_field=models.DateTimeField(),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                ("assignment", models.TextField(verbose_name="Assignment")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=255,
                        verbose_name="Difficulty",
                    ),
                ),
                ("config_data", models.JSONField(default=dict, verbose_name="Config data")),
                (
                    "validation_script",
                    models.TextField(
                        help_text="Validates resources managed by the terraform code", verbose_name="Validation script"
                    ),
                ),
                (
                    "code_template",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What the user will see when they start the tutorial",
                        verbose_name="Code template",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tutorials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="tutorials", to="providers.provider"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="tutorials", to="tutorials.tutorialtag")),
            ],
            options={
                "verbose_name": "Tutorial",
                "verbose_name_plural": "Tutorials",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TutorialSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=main.apps.core.models.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                        output_field=models.DateTimeField(),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("code", models.TextField(verbose_name="Code")),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="tutorials.tutorial"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Submission",
                "verbose_name_plural": "Tutorial Submissions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="tutorial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["config_data"], name="tutorials_t_config__45d5b6_gin"
            ),
        ),
    ]
