# Generated by Django 5.2.8 on 2025-11-20 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from main.apps.core.models import UUIDv7


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=UUIDv7(), editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Tutorial",
                "verbose_name_plural": "Tutorials",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TutorialStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=UUIDv7(), editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100, help_text="The order of the step in the tutorial", verbose_name="Order"
                    ),
                ),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="tutorials.tutorial"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Step",
                "verbose_name_plural": "Tutorial Steps",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="TutorialStepSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=UUIDv7(), editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("code", models.TextField(verbose_name="Code")),
                (
                    "tutorial_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="tutorials.tutorialstep",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Step Submission",
                "verbose_name_plural": "Tutorial Step Submissions",
                "ordering": ("-created_at",),
            },
        ),
    ]
