# Generated by Django 6.0 on 2026-01-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0003_provideruserproject_configuration_attempts_and_more"),
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialsubmission",
            name="provider_user_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="providers.provideruserproject",
            ),
        ),
    ]
