# Generated by Django 6.0 on 2026-01-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0002_tutorialsubmission_provider_user_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Review"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
