# Generated by Django 6.0 on 2026-01-27 10:24

import django.db.models.deletion
import main.apps.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0003_alter_tutorial_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "id",
                    models.UUIDField(
                        default=main.apps.core.models.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                        output_field=models.DateTimeField(),
                    ),
                ),
                ("feedback", models.TextField(verbose_name="Review feedback")),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="tutorials.tutorial"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Review",
                "verbose_name_plural": "Tutorial Reviews",
                "ordering": ("-created_at",),
            },
        ),
    ]
