# Generated by Django 5.2.8 on 2025-11-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0003_provider_providerproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="provider",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutorials",
                to="tutorials.provider",
            ),
            preserve_default=False,
        ),
    ]
