# Generated by Django 5.2.8 on 2025-11-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0004_tutorial_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialstepsubmission",
            name="provider_project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="tutorials.providerproject",
            ),
            preserve_default=False,
        ),
    ]
