# Generated by Django 6.0 on 2026-01-28 08:44

import django.db.models.deletion
import main.apps.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0004_tutorial_review_feedback_tutorialreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialVote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "id",
                    models.UUIDField(
                        default=main.apps.core.models.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                        output_field=models.DateTimeField(),
                    ),
                ),
                ("vote_value", models.IntegerField(choices=[(1, "Upvote"), (-1, "Downvote")], verbose_name="Vote")),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="tutorials.tutorial"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Vote",
                "verbose_name_plural": "Tutorial Votes",
                "ordering": ("-created_at",),
                "constraints": [models.UniqueConstraint(fields=("tutorial", "user"), name="unique_tutorial_user_vote")],
            },
        ),
    ]
