# Generated by Django 6.0 on 2026-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0005_tutorialvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("executing", "Executing"),
                    ("validating", "Validating"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
