# Generated by Django 5.2.8 on 2025-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0005_tutorialstepsubmission_provider_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                default="beginner",
                max_length=255,
                verbose_name="Difficulty",
            ),
        ),
    ]
