# Generated by Django 5.2.8 on 2025-11-24 13:59

from django.db import migrations, models

from main.apps.core.models import UUIDv7


class Migration(migrations.Migration):
    dependencies = [("tutorials", "0006_tutorial_difficulty")]

    operations = [
        migrations.CreateModel(
            name="TutorialTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=UUIDv7(), editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Tutorial Tag",
                "verbose_name_plural": "Tutorial Tags",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="tutorial",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tutorials", to="tutorials.tutorialtag"),
        ),
    ]
