# Generated by Django 5.2.8 on 2025-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0007_tutorialtag_tutorial_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialstep",
            name="assignment",
            field=models.TextField(default="", help_text="Full assignment for the step", verbose_name="Assignment"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tutorialstep",
            name="description",
            field=models.TextField(help_text="The brief description of the step", verbose_name="Description"),
        ),
    ]
