# Generated by Django 6.0 on 2025-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0008_tutorialstep_assignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialstep",
            name="code_skeleton",
            field=models.TextField(
                blank=True, default="", help_text="The skeleton of the code", verbose_name="Code skeleton"
            ),
        ),
    ]
