# Generated by Django 6.0 on 2026-01-29 12:12

import django.db.models.deletion
import main.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0009_tutorialsubmission_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialSubmissionEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "id",
                    models.UUIDField(
                        default=main.apps.core.models.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                        output_field=models.DateTimeField(),
                    ),
                ),
                (
                    "event_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executing", "Executing"),
                            ("execution_succeeded", "Execution Succeeded"),
                            ("execution_failed", "Execution Failed"),
                            ("validating", "Validating"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        max_length=255,
                        verbose_name="Event status",
                    ),
                ),
                ("exit_code", models.IntegerField(verbose_name="Exit code")),
                ("stdout", models.TextField(blank=True, default="", verbose_name="Output")),
                ("error", models.TextField(blank=True, default="", verbose_name="Error")),
                (
                    "tutorial_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tutorials.tutorialsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial submission event",
                "verbose_name_plural": "Tutorial submission events",
                "ordering": ("-created_at",),
            },
        ),
    ]
