# Generated by Django 6.0 on 2025-12-17 12:51

import main.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0009_tutorialstep_solution_skeleton"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="creation_time",
            field=models.GeneratedField(
                db_persist=True,
                expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                output_field=models.DateTimeField(),
            ),
        ),
        migrations.AddField(
            model_name="providerproject",
            name="creation_time",
            field=models.GeneratedField(
                db_persist=True,
                expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                output_field=models.DateTimeField(),
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="creation_time",
            field=models.GeneratedField(
                db_persist=True,
                expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                output_field=models.DateTimeField(),
            ),
        ),
        migrations.AddField(
            model_name="tutorialstep",
            name="creation_time",
            field=models.GeneratedField(
                db_persist=True,
                expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                output_field=models.DateTimeField(),
            ),
        ),
        migrations.AddField(
            model_name="tutorialstepsubmission",
            name="creation_time",
            field=models.GeneratedField(
                db_persist=True,
                expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                output_field=models.DateTimeField(),
            ),
        ),
        migrations.AddField(
            model_name="tutorialtag",
            name="creation_time",
            field=models.GeneratedField(
                db_persist=True,
                expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                output_field=models.DateTimeField(),
            ),
        ),
    ]
