# Generated by Django 6.0 on 2026-01-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0010_provider_creation_time_providerproject_creation_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorialstepsubmission",
            name="provider_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="tutorials.providerproject",
            ),
        ),
    ]
