# Generated by Django 6.0 on 2026-02-01 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0011_remove_tutorialsubmission_result"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="starred_by",
            field=models.ManyToManyField(blank=True, related_name="starred_tutorials", to=settings.AUTH_USER_MODEL),
        ),
    ]
