# Generated by Django 6.0 on 2026-01-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0011_alter_tutorialstepsubmission_provider_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                default="draft",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
