# Generated by Django 6.0 on 2026-01-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0012_tutorial_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="provider_id",
            field=models.CharField(
                default="google",
                help_text="Should match Allauth SocialApp provider",
                max_length=255,
                verbose_name="Provider ID",
            ),
            preserve_default=False,
        ),
    ]
