# Generated by Django 6.0 on 2026-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0012_tutorial_starred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialsubmission",
            name="gcp_executor_job_execution_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="GCP Executor Job Execution ID"
            ),
        ),
        migrations.AddField(
            model_name="tutorialsubmission",
            name="gcp_validator_job_execution_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="GCP Validator Job Execution ID"
            ),
        ),
    ]
