# Generated by Django 6.0 on 2026-01-12 13:31

import django.db.models.deletion
import main.apps.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0013_provider_provider_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=main.apps.core.models.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                        output_field=models.DateTimeField(),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
            ],
            options={
                "verbose_name": "Tutorial Project",
                "verbose_name_plural": "Tutorial Projects",
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="providerproject",
            name="unique_provider_user",
        ),
        migrations.RemoveField(
            model_name="tutorialstepsubmission",
            name="provider_project",
        ),
        migrations.AddField(
            model_name="tutorialproject",
            name="tutorial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="tutorials.tutorial"
            ),
        ),
        migrations.AddField(
            model_name="tutorialproject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="providerproject",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="providerproject",
            name="user",
        ),
        migrations.AddConstraint(
            model_name="tutorialproject",
            constraint=models.UniqueConstraint(fields=("tutorial", "user"), name="unique_tutorial_user_project"),
        ),
        migrations.DeleteModel(
            name="ProviderProject",
        ),
    ]
