# Generated by Django 6.0 on 2026-01-12 13:38

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0014_tutorialproject_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialproject",
            name="config_data",
            field=models.JSONField(default=dict, verbose_name="Config data"),
        ),
        migrations.AddIndex(
            model_name="tutorialproject",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["config_data"], name="tutorials_t_config__3fbfb3_gin"
            ),
        ),
    ]
