# Generated by Django 6.0 on 2026-01-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0015_tutorialproject_config_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
