# Generated by Django 6.0 on 2026-01-13 11:20

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0016_tutorialproject_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="config_data",
            field=models.JSONField(default=dict, verbose_name="Config data"),
        ),
        migrations.AddIndex(
            model_name="tutorial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["config_data"], name="tutorials_t_config__45d5b6_gin"
            ),
        ),
    ]
