# Generated by Django 6.0 on 2026-01-13 12:45

import main.apps.tutorials.models.tutorial_project
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0017_tutorial_config_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialproject",
            name="tf_state_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=main.apps.tutorials.models.tutorial_project.tf_state_file_path,
                verbose_name="Terraform state file",
            ),
        ),
    ]
