# Generated by Django 6.0 on 2026-01-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0018_tutorialproject_tf_state_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialstepsubmission",
            name="tutorial_project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="tutorials.tutorialproject",
            ),
            preserve_default=False,
        ),
    ]
