# Generated by Django 6.0 on 2026-01-16 13:02

import django.db.models.deletion
from django.db import migrations, models


def populate_tutorial_field(apps, schema_editor):
    TutorialStepSubmission = apps.get_model("tutorials", "TutorialStepSubmission")
    qs = TutorialStepSubmission.objects.select_related("tutorial_step__tutorial")
    for submission in qs:
        submission.tutorial_id = submission.tutorial_step.tutorial_id
        submission.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0019_tutorialstepsubmission_tutorial_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialstepsubmission",
            name="tutorial",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="tutorials.tutorial",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_tutorial_field, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="tutorialstepsubmission",
            name="tutorial_step",
        ),
        migrations.DeleteModel(
            name="TutorialStep",
        ),
    ]
