# Generated by Django 6.0 on 2026-01-16 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0020_remove_tutorialstepsubmission_tutorial_step_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TutorialStepSubmission",
            new_name="TutorialSubmission",
        ),
        migrations.AlterModelOptions(
            name="tutorialsubmission",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Tutorial Submission",
                "verbose_name_plural": "Tutorial Submissions",
            },
        ),
        migrations.RemoveField(
            model_name="tutorialproject",
            name="tf_state_file",
        ),
        migrations.AddField(
            model_name="tutorial",
            name="code_template",
            field=models.TextField(blank=True, default="", verbose_name="Code template"),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="validation_script",
            field=models.TextField(
                default="",
                help_text="Validates resources managed by the terraform code",
                verbose_name="Validation script",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Review"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=255,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="tutorialproject",
            name="status",
            field=models.CharField(
                choices=[("created", "Created"), ("configured", "Configured"), ("error", "Error")],
                default="created",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
