# Generated by Django 6.0 on 2026-01-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0021_rename_tutorialstepsubmission_tutorialsubmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="assignment",
            field=models.TextField(default="", verbose_name="Assignment"),
            preserve_default=False,
        ),
    ]
