# Generated by Django 6.0 on 2026-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0022_tutorial_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="code_template",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What the user will see when they start the tutorial",
                verbose_name="Code template",
            ),
        ),
    ]
