# Generated by Django 6.0 on 2026-01-22 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("text", models.CharField(max_length=255, verbose_name="Notification text")),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("success", "Success"), ("warning", "Warning"), ("error", "Error")],
                        default="info",
                        max_length=255,
                        verbose_name="Notification level",
                    ),
                ),
                ("dispatched", models.BooleanField(default=False, verbose_name="Dispatched")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("-created_at",),
            },
        ),
    ]
