# Generated by Django 6.0 on 2026-01-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="read",
            field=models.BooleanField(default=False, verbose_name="Read"),
        ),
    ]
