# Generated by Django 6.0 on 2026-01-25 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="read",
        ),
    ]
