# Generated by Django 5.2.8 on 2025-11-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("username", ""), _negated=True),
                fields=("username",),
                name="unique_non_empty_username",
            ),
        ),
    ]
