# Generated by Django 5.2.8 on 2025-11-20 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_admin_user_unique_non_empty_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_manager_name": "objects",
                "ordering": ("-created_at",),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
