# Generated by Django 6.0 on 2025-12-17 12:51

import main.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="creation_time",
            field=models.GeneratedField(
                db_persist=True,
                expression=main.apps.core.models.UUIDExtractTimestamp("id"),
                output_field=models.DateTimeField(),
            ),
        ),
    ]
