# Generated by Django 5.2.8 on 2025-11-20 12:17

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        UnaccentExtension(),
    ]
